name: serdp_modeling
channels:
  - defaults # Order matters tried defaults first
  - conda-forge
dependencies:
  - python>=3.6
  - ipython=7.8.0
  - jupyter=1.0.0
  - numpy=1.17.2
  - pandas=0.25.1
  - scipy=1.3.1
  - matplotlib=3.1.1
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - pip=19.1.1=py37_0
  - pyyaml=5.2
  - sympy=1.5.1
  - pip:                            # Packages installed from PyPI
    - arviz==0.6.1
    - theano==1.0.4
    - jedi==0.17.2
  - pymc3=3.7
  #   - geopandas==0.6.2
